on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-18.04, r: '3.6'}

    steps:
      - uses: actions/checkout@v2
      - name: sysdeps
        run: |
          # sudo add-apt-repository ppa:cran/travis
          # sudo apt-get -y update
          # sudo apt-get install -y libgit2-dev libcurl4-openssl-dev
          # sudo apt-get install -y make git-core libxml2-dev libgit2-dev libssl-dev zlib1g-dev libssh2-1-dev pandoc pandoc-citeproc libcurl4-openssl-dev
          # sudo apt-get install -y make git-core libxml2-dev libgit2-dev libssl-dev zlib1g-dev libssh2-1-dev pandoc pandoc-citeproc 
          
        env: 
          DEBIAN_FRONTEND: noninteractive

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          echo $sysreqs
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}
